name: form_input
description: formz input
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.16.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  formz: ^0.4.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  very_good_analysis: ^2.4.0