medical_names = [
    "Global Pharmacy",
    "Healthcare Company",
    "Beacons Pharmaceuticals",
    "Medical Products",
    "Medical Supply",
    "Surgical House",
    "Superior Healthcare",
    "Medical Accessories",
    "Alpha Medical",
    "Medical Consumables",
    "First Aid Distributions",
    "Brilliant Medical System",
    "Medi Print",
    "Medic Marketing",
    "Medical Systems",
    "Lifeline Corporation",
    "Medaid Solutions",
    "Pharmatrial",
    "Global Medicare",
    "SeniorCare",
    "Wellness Studio",
    "Active Moments",
    "Lifeline Corporation",
    "Health Ware",
    "HearingPartners",
    "Medi-Life",
    "Range Pharma",
    "Hospitech Marketing",
    "Wellness Trading",
    "Global Health",
    "Wellchem",
]
