from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(900, 850)
        self.widget = QtWidgets.QWidget(Dialog)
        self.widget.setGeometry(QtCore.QRect(0, 0, 901, 900))
        self.widget.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.widget.setObjectName("widget")
        self.widget_2 = QtWidgets.QWidget(self.widget)
        self.widget_2.setGeometry(QtCore.QRect(-1, 0, 901, 71))
        self.widget_2.setStyleSheet("background-color: rgb(0, 153, 112);")
        self.widget_2.setObjectName("widget_2")
        self.back_pushButton = QtWidgets.QPushButton(self.widget_2)
        self.back_pushButton.setGeometry(QtCore.QRect(10, 10, 101, 41))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.back_pushButton.setFont(font)
        self.back_pushButton.setStyleSheet("background-color: rgb(255, 255, 255);\n"
                                           "color: rgb(10, 89, 83);\n"
                                           "border-radius:10px;")
        self.back_pushButton.setObjectName("back_pushButton")
        self.scrollArea = QtWidgets.QScrollArea(self.widget)
        self.scrollArea.setGeometry(QtCore.QRect(0, 70, 901, 791))
        self.scrollArea.setStyleSheet("border: none;")
        self.scrollArea.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.scrollArea.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 901, 791))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents)
        self.verticalLayout.setContentsMargins(55, 9, 55, -1)
        self.verticalLayout.setSpacing(30)
        self.verticalLayout.setObjectName("verticalLayout")
        self.Add_medical = QtWidgets.QWidget(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Add_medical.sizePolicy().hasHeightForWidth())
        self.Add_medical.setSizePolicy(sizePolicy)
        self.Add_medical.setMinimumSize(QtCore.QSize(0, 250))
        self.Add_medical.setObjectName("Add_medical")
        self.label = QtWidgets.QLabel(self.Add_medical)
        self.label.setGeometry(QtCore.QRect(130, 50, 531, 91))
        font = QtGui.QFont()
        font.setPointSize(-1)
        font.setBold(True)
        self.label.setFont(font)
        self.label.setStyleSheet("color: rgb(0, 153, 112);\n"
                                 "font-weight: 600;\n"
                                 "font-size: 23px;")
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.add_pushButton = QtWidgets.QPushButton(self.Add_medical)
        self.add_pushButton.setGeometry(QtCore.QRect(240, 160, 301, 51))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        self.add_pushButton.setFont(font)
        self.add_pushButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.add_pushButton.setStyleSheet("background-color: rgb(0, 153, 112);\n"
                                          "color: rgb(255, 255, 255);\n"
                                          "border-radius:10px;")
        self.add_pushButton.setObjectName("add_pushButton")
        self.verticalLayout.addWidget(self.Add_medical)
        self.widget_3 = QtWidgets.QWidget(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget_3.sizePolicy().hasHeightForWidth())
        self.widget_3.setSizePolicy(sizePolicy)
        self.widget_3.setMinimumSize(QtCore.QSize(0, 250))
        self.widget_3.setStyleSheet("border-radius:10px;\n"
                                    "background-color: rgb(0, 153, 112);")
        self.widget_3.setObjectName("widget_3")
        self.label_2 = QtWidgets.QLabel(self.widget_3)
        self.label_2.setGeometry(QtCore.QRect(30, 30, 67, 17))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.widget_3)
        self.label_3.setGeometry(QtCore.QRect(30, 80, 81, 17))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.widget_3)
        self.label_4.setGeometry(QtCore.QRect(30, 120, 91, 17))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_4.setFont(font)
        self.label_4.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_4.setObjectName("label_4")
        self.shopName_text = QtWidgets.QLabel(self.widget_3)
        self.shopName_text.setGeometry(QtCore.QRect(130, 30, 161, 21))
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setBold(True)
        self.shopName_text.setFont(font)
        self.shopName_text.setStyleSheet("color: rgb(255, 255, 255);")
        self.shopName_text.setObjectName("shopName_text")
        self.address_text = QtWidgets.QLabel(self.widget_3)
        self.address_text.setGeometry(QtCore.QRect(130, 70, 361, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.address_text.setFont(font)
        self.address_text.setStyleSheet("color: rgb(255, 255, 255);")
        self.address_text.setObjectName("address_text")
        self.phoneNumber_text = QtWidgets.QLabel(self.widget_3)
        self.phoneNumber_text.setGeometry(QtCore.QRect(130, 120, 151, 21))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.phoneNumber_text.setFont(font)
        self.phoneNumber_text.setStyleSheet("color: rgb(255, 255, 255);")
        self.phoneNumber_text.setObjectName("phoneNumber_text")
        self.label_14 = QtWidgets.QLabel(self.widget_3)
        self.label_14.setGeometry(QtCore.QRect(30, 160, 61, 31))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label_14.setFont(font)
        self.label_14.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_14.setAlignment(QtCore.Qt.AlignLeading | QtCore.Qt.AlignLeft | QtCore.Qt.AlignVCenter)
        self.label_14.setObjectName("label_14")
        self.email_text = QtWidgets.QLabel(self.widget_3)
        self.email_text.setGeometry(QtCore.QRect(130, 160, 221, 21))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.email_text.setFont(font)
        self.email_text.setStyleSheet("color: rgb(255, 255, 255);")
        self.email_text.setObjectName("email_text")
        self.label_16 = QtWidgets.QLabel(self.widget_3)
        self.label_16.setGeometry(QtCore.QRect(30, 210, 91, 17))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_16.setFont(font)
        self.label_16.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_16.setObjectName("label_16")
        self.pincode_text = QtWidgets.QLabel(self.widget_3)
        self.pincode_text.setGeometry(QtCore.QRect(130, 210, 91, 17))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.pincode_text.setFont(font)
        self.pincode_text.setStyleSheet("color: rgb(255, 255, 255);")
        self.pincode_text.setObjectName("pincode_text")
        self.verticalLayout.addWidget(self.widget_3)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.scrollArea.raise_()
        self.widget_2.raise_()

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.back_pushButton.setText(_translate("Dialog", "Back"))
        self.label.setText(_translate("Dialog", "Add New Medical Shop!"))
        self.add_pushButton.setText(_translate("Dialog", "Add"))
        self.label_2.setText(_translate("Dialog", "Name:"))
        self.label_3.setText(_translate("Dialog", "Address:"))
        self.label_4.setText(_translate("Dialog", "Phone No:"))
        self.shopName_text.setText(_translate("Dialog", "Pharma Medical"))
        self.address_text.setText(_translate("Dialog", "Shop No:4,Narayan Nagar,Thane"))
        self.phoneNumber_text.setText(_translate("Dialog", "091234566788"))
        self.label_14.setText(_translate("Dialog", "Email:"))
        self.email_text.setText(_translate("Dialog", "medishop@gmail.com"))
        self.label_16.setText(_translate("Dialog", "Pincode:"))
        self.pincode_text.setText(_translate("Dialog", "401101"))
