# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Frames/Messages.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class UI_Message(object):
    def setupUi(self, UI_Message,text):
        UI_Message.setObjectName("UI_Message")
        UI_Message.resize(900, 850)
        self.widget = QtWidgets.QWidget(UI_Message)
        self.widget.setGeometry(QtCore.QRect(0, 0, 921, 850))
        self.widget.setStyleSheet("background-color :rgb(255, 255, 255)")
        self.widget.setObjectName("widget")
        self.Title = QtWidgets.QLabel(self.widget)
        self.Title.setGeometry(QtCore.QRect(0, 0, 900, 850))
        font = QtGui.QFont()
        font.setPointSize(28)
        font.setBold(True)
        self.Title.setFont(font)
        self.Title.setStyleSheet("color: rgb(0, 0, 0);")
        self.Title.setAlignment(QtCore.Qt.AlignCenter)
        self.Title.setObjectName("Title")
        self.text = text

        self.retranslateUi(UI_Message)
        QtCore.QMetaObject.connectSlotsByName(UI_Message)

    def retranslateUi(self, UI_Message):
        _translate = QtCore.QCoreApplication.translate
        UI_Message.setWindowTitle(_translate("UI_Message", "Sign Up"))
        self.Title.setText(_translate("UI_Message", self.text))
