# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Frames/searchFrame.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(900, 850)
        Form.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(140, 50, 641, 134))
        self.label.setStyleSheet("color: rgb(41, 47, 127);\n"
"font: 600 13pt \"Source Serif Pro\";\n"
"font-size: 48px;")
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "PharmaServices"))
        self.label.setText(_translate("Form", "<html><head/><body><p>Get Your <span style=\" font-weight:700;\">MEDICINE</span> in </p><p><span style=\" font-weight:700;\">OUR</span> nearby Medical Shops!</p></body></html>"))
