# Generated by Django 4.0.1 on 2022-01-27 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Medical',
            fields=[
                ('medicalId', models.IntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=20)),
                ('address', models.CharField(max_length=100)),
                ('pincode', models.IntegerField()),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('phone', models.IntegerField(default=0)),
                ('email', models.EmailField(max_length=100)),
                ('website', models.URLField(max_length=100)),
                ('image', models.ImageField(upload_to='images/<django.db.models.fields.CharField>_<django.db.models.fields.IntegerField>_<django.db.models.fields.DateTimeField>')),
            ],
        ),
    ]
