# Generated by Django 4.0.2 on 2022-04-29 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pharmacy", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="popularmedicine",
            name="latitude",
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name="popularmedicine",
            name="longitude",
            field=models.FloatField(default=0.0),
        ),
    ]
