# Generated by Django 4.0.1 on 2022-01-27 09:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medical',
            name='image',
        ),
    ]
