# Generated by Django 4.0.2 on 2022-02-23 17:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MedicineClass',
        ),
    ]
