# Generated by Django 4.0.1 on 2022-02-06 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medical',
            name='image',
            field=models.ImageField(blank=True, upload_to='images/'),
        ),
    ]
