# Generated by Django 4.0.1 on 2022-01-27 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0002_remove_medical_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='medical',
            name='image',
            field=models.ImageField(default='images/default.jpg', upload_to='images/<django.db.models.fields.CharField>_<django.db.models.fields.IntegerField>_<django.db.models.fields.DateTimeField>'),
        ),
    ]
