# Generated by Django 4.0.1 on 2022-02-02 12:40

from django.db import migrations, models
import django.db.models.deletion
import pharmacy.api.views.medicine.list
import pharmacy.api.views.medicine.search


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0004_alter_medical_image_alter_medical_website'),
    ]

    operations = [
        migrations.CreateModel(
            name='MedicineClass',
            fields=[
                ('medicine_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='pharmacy.medicine')),
            ],
            bases=(pharmacy.api.views.medicine.list.MedicineViewList, pharmacy.api.views.medicine.search.MedicineSearch, 'pharmacy.medicine'),
        ),
    ]
